name: 'collect-release-changelog'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'The token of github'
    required: true
  folder:
    description: 'The folder of changelog'
    required: false
  langs:
    description: 'the langs of changelog'
    required: false
  file_name:
    description: 'the file name to update changelog markdown'
    required: false
  tag_name:
    description: 'the tag name of release'
    required: false

# Define your outputs here.
outputs:
  changed_files:
    description: 'the files changed'

runs:
  using: node20
  main: dist/index.js
