name: Release changelog

on:
  release:
    types: [published]

jobs:
  update-changelog-after-publish-a-release:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./changlog
          langs: en,zh
          tag_name: github.event.release.tag_name
          file_name: changlog.md

      - name: Create Pull Request
        uses: dustinirving/create-pr@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[Auto changlod]'
          base: main
          head: ${{ github.ref_name }}
          labels: release
          body: 'update changelog of ${{  github.event.release.tag_name }}'
